<?xml version="1.0" encoding="UTF-8"?>
<Document xmlns="urn:iso:std:iso:20022:tech:xsd:pain.008.001.02" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:iso:std:iso:20022:tech:xsd:pain.008.001.02 pain.008.001.02.xsd">
    <CstmrDrctDbtInitn>
        <GrpHdr>
            <MsgId>EX-SEPA-MsgID-###TIMESTAMP###</MsgId>
            <CreDtTm>###DATETIME###.000Z</CreDtTm>
            <NbOfTxs>###NUMOFTRANSACTIONS###</NbOfTxs>
            <CtrlSum>###SUMOFTRANSACTIONS###</CtrlSum>
            <InitgPty>
                <Nm>###CREDITOR###</Nm>
            </InitgPty>
        </GrpHdr>
        <PmtInf>
            <PmtInfId>EX-SEPA-PMT-ID2-###TIMESTAMP###</PmtInfId>
            <PmtMtd>DD</PmtMtd>
            <BtchBookg>true</BtchBookg>
            <NbOfTxs>###NUMOFTRANSACTIONS###</NbOfTxs>
            <CtrlSum>###SUMOFTRANSACTIONS###</CtrlSum>
            <PmtTpInf>
                <SvcLvl>
                    <Cd>SEPA</Cd>
                </SvcLvl>
                <LclInstrm>
                    <Cd>CORE</Cd>
                </LclInstrm>
                <SeqTp>RCUR</SeqTp>
            </PmtTpInf>
            <ReqdColltnDt>###COLLECTIONDATE###</ReqdColltnDt>
            <Cdtr>
                <Nm>###CREDITOR###</Nm>
            </Cdtr>
            <CdtrAcct>
                <Id>
                    <IBAN>###CREDITORIBAN###</IBAN>
                </Id>
            </CdtrAcct>
            <CdtrAgt>
                <FinInstnId>
                    <BIC>###CREDITORBIC###</BIC>
                </FinInstnId>
            </CdtrAgt>
            <ChrgBr>SLEV</ChrgBr>
            <CdtrSchmeId>
                <Id>
                    <PrvtId>
                        <Othr>
                            <Id>###MANDATEID###</Id>
                            <SchmeNm>
                                <Prtry>SEPA</Prtry>
                            </SchmeNm>
                        </Othr>
                    </PrvtId>
                </Id>
            </CdtrSchmeId>
            ###TRANSACTIONS###
        </PmtInf>
    </CstmrDrctDbtInitn>
</Document>
